site_name: "Władysław Witkowski"
theme:
  name: material
  logo: assets/google-play-games-services-icon.png
  favicon: assets/google-play-games-services-icon.png
  palette:
    scheme: slate
    primary: black
    accent: custom
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - projects