site_name: "Google AdMob: Unreal Engine Plugin Documentation"
site_url: https://deepinnothing.github.io/documentation/unreal-engine/google-admob
site_dir: ../../../site/documentation/unreal-engine/google-admob
theme:
  name: material
  logo: assets/google-admob-icon.png
  favicon: assets/google-admob-icon.png
  palette:
    scheme: slate
    primary: black
    accent: custom
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - index.md
  - enable-test-ads.md
  - user-messaging-platform.md
plugins: 
  - search
  - git-revision-date-localized