site_name: "Google AdMob: Unreal Engine Plugin Documentation"
site_url: https://deepinnothing.github.io/documentation/unreal-engine/google-admob
site_dir: ../../../site/documentation/unreal-engine/google-admob
theme:
  name: material
  logo: assets/google-admob-icon.png
  favicon: assets/google-admob-icon.png
  palette:
    scheme: slate
    primary: black
    accent: custom
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
nav:
  - index.md
  - enable-test-ads.md
  - user-messaging-platform.md
  - Ad formats:
    - ad-formats/app-open-ads.md
    - ad-formats/banner-ads.md
    - ad-formats/interstitial-ads.md
    - ad-formats/rewarded-ads.md
    - ad-formats/rewarded-interstitial-ads.md
  - mediation.md
  - Tools and debugging:
    - Ad inspector:
      - ad-inspector.md
      - ad-inspector/launch-ad-inspector.md
      - Verify adapter integrations: https://developers.google.com/admob/android/ad-inspector/verify-adapter-integrations
      - Test ad units: https://developers.google.com/admob/android/ad-inspector/test-ad-units
      - Troubleshoot ad units: https://developers.google.com/admob/android/ad-inspector/troubleshoot-ad-units
      - Troubleshoot privacy settings: https://developers.google.com/admob/android/ad-inspector/troubleshoot-privacy-settings
      - Copy troubleshooting output: https://developers.google.com/admob/android/ad-inspector/copy-troubleshooting-output
plugins: 
  - search
  - git-revision-date-localized