site_name: "Unity LevelPlay: Unreal Engine Plugin Documentation"
site_url: https://deepinnothing.github.io/documentation/unreal-engine/levelplay
site_dir: ../../../site/documentation/unreal-engine/levelplay
theme:
  name: material
  logo: assets/ironsource-icon.png
  favicon: assets/ironsource-icon.png
  palette:
    scheme: slate
    primary: black
    accent: custom
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
nav:
  - Get started: 
    - Getting started: index.md
    - Integration: integration.md
    - LevelPlay SDK Changelog: https://developers.is.com/ironsource-mobile/unity/sdk-change-log/
  - Regulations and settings:
    - regulations-and-settings/regulation-advanced-settings.md
    - regulations-and-settings/advanced-settings.md
    - regulations-and-settings/impression-level-revenue-integration.md
    - AdInfo data: regulations-and-settings/adinfo-data.md
    - Google's data safety questionnaire: https://developers.is.com/ironsource-mobile/general/googles-data-safety-questionnaire-full/
    - Apple's app privacy questionnaire: https://developers.is.com/ironsource-mobile/apples-privacy-questionnaire-answers-ironsource/
  - Ad formats:
    - Rewarded ads: ad-formats/rewarded.md
    - Interstitial: ad-formats/interstitial.md
    - Banner/MREC: ad-formats/banner.md
  - Mediated networks:
    - Add mediation networks: mediation-networks/mediation.md
    - Ad Quality supported ad sources: https://developers.is.com/ironsource-mobile/unity/supported-ad-sources/
  - Test your integration:
    - LevelPlay integration test suite: https://developers.is.com/ironsource-mobile/unity/unity-levelplay-test-suite/
    - Integration Helper: test-your-integration/integration-helper.md
    - Testing module: https://developers.is.com/ironsource-mobile/unity/integration-testing/
    - "Troubleshooting: I don't see ads in my app": https://developers.is.com/ironsource-mobile/unity/troubleshooting-dont-see-ads-app/
    - "Troubleshooting: TCF Consent Log": https://developers.is.com/ironsource-mobile/unity/troubleshooting-tcf-consent-log/
    - Test Ad Quality SDK: https://developers.is.com/ironsource-mobile/unity/test-ad-quality-sdk-integration/
plugins: 
  - search
  - git-revision-date-localized