name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      
      - name: Build Google Play Games Services
        run: |
          cd documentation/unreal-engine/google-play-games-services
          mkdocs build

      - name: Build Google AdMob
        run: |
          cd documentation/unreal-engine/google-admob
          mkdocs build

      - name: Build Google UMP
        run: |
          cd documentation/unreal-engine/google-ump
          mkdocs build
      
      - name: Include ZIP files
        run: |
          mkdir -p site/sample-projects/unreal-engine/google-admob
          cp sample-projects/unreal-engine/google-admob/*.zip site/sample-projects/unreal-engine/google-admob/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site